# Generated by Django 2.1.7 on 2019-03-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_banner', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service_bg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('contact_home', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('contact_modal', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('project_banner', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_banner', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
