# Generated by Django 2.1.7 on 2019-03-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('year', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('technology', models.CharField(blank=True, max_length=200, null=True)),
                ('summery', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
