# Generated by Django 2.1.7 on 2019-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
