# Generated by Django 2.1.7 on 2019-03-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190305_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacategory',
            old_name='name',
            new_name='dataCategory',
        ),
    ]
