# Generated by Django 2.1.7 on 2019-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190302_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
